[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_guardian = "Guard1an1111111111111111111111111111111111"

[programs.mainnet]
solana_guardian = "Guard1an1111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "python run_tests.py"
